export const LANG_COLORS = {
  "C#": "#178600",
  TypeScript: "#3178c6",
  JavaScript: "#e8b339",
  Java: "#b07219",
  Python: "#3572A5",
};
export const REPOS = [
  {
    lang: "C#",
    name: "CashDash",
    url: "https://github.com/W3ndig0u0/CashDash",
    desc: "Ruttmotor för gränsöverskridande betalningar över 6 blockkedjor, fintech och SWIFT.",
    topics: [
      "angularjs",
      "crypto",
      "csharp",
      "ethereum",
      "blockchain",
      "bank",
      "fintech",
    ],
    status: "active",
  },
  {
    lang: "TypeScript",
    name: "GameBacklog-Tracker",
    url: "https://github.com/W3ndig0u0/GameBacklog-Tracker",
    desc: "Fullstack gaming-aggregator och backlog-spårare via IGDB, Netflix-likt UI.",
    topics: [
      "react",
      "typescript",
      "spring-boot",
      "postgresql",
      "fullstack",
      "backlog",
      "game-tracker",
    ],
    status: "active",
  },
  {
    lang: "JavaScript",
    name: "PersonalSaltSocialMedia",
    url: "https://github.com/W3ndig0u0/PersonalSaltSocialMedia",
    desc: "Fullstack social media-app, en Threads-klon.",
    topics: ["fullstack", "social-media", "threads-clone"],
    status: "active",
  },
  {
    lang: "Java",
    name: "Kitsune",
    url: "https://github.com/W3ndig0u0/Kitsune",
    desc: "Fullstack streamingapplikation för anime.",
    topics: ["fullstack", "streaming", "anime"],
    status: "active",
  },
  {
    lang: "TypeScript",
    name: "Books-Quotes-Management",
    url: "https://github.com/W3ndig0u0/Books-Quotes-Management-System-Internship",
    desc: "Hanteringssystem för böcker och citat, byggt under praktik.",
    topics: ["internship", "typescript", "management-system"],
    status: "active",
  },
  {
    lang: "Java",
    name: "Fire-emblem",
    url: "https://github.com/W3ndig0u0/Fire-emblem",
    desc: "Taktisk RPG-motor inspirerad av Fire Emblem, byggd med Java och Spring Boot.",
    topics: ["java", "spring-boot", "rpg-engine", "game-dev"],
    status: "active",
  },
  {
    lang: "Python",
    name: "discord-Anime-Art-bot",
    url: "https://github.com/W3ndig0u0/discord-Anime-Art-bot",
    desc: "Discord-bot för att generera bilder.",
    topics: ["discord-bot", "python", "image-generation"],
    status: "active",
  },
  {
    lang: "JavaScript",
    name: "AiArtGeneration",
    url: "https://github.com/W3ndig0u0/AiArtGeneration",
    desc: "Utforskar AI-genererad konst med hjälp av artificiell intelligens.",
    topics: ["ai", "image-generation", "javascript"],
    status: "active",
  },
  {
    lang: "JavaScript",
    name: "Kanime",
    url: "https://github.com/W3ndig0u0/Kanime",
    desc: "Som MAL, fast sämre :)",
    topics: ["anime", "tracker", "javascript"],
    status: "active",
  },
  {
    lang: "JavaScript",
    name: "TikTokManga",
    url: "https://github.com/W3ndig0u0/TikTokManga",
    desc: "Automatiserar mangakapitel till TikTok-videor. LEGACY.",
    topics: ["automation", "manga", "legacy"],
    status: "archived",
  },
  {
    lang: "ShaderLab",
    name: "EscapeRoom",
    url: "https://github.com/W3ndig0u0/EscapeRoom",
    desc: "Unity-baserat 3D escape room-spel utvecklat som universitetsprojekt.",
    topics: ["unity", "3d", "escape-room", "game-dev"],
    status: "active",
  },
  {
    lang: "C#",
    name: "MuseDash",
    url: "https://github.com/W3ndig0u0/MuseDash",
    desc: "Rhythm game inspirerat av Muse Dash.",
    topics: ["unity", "rhythm-game", "game-dev"],
    status: "active",
  },
  {
    lang: "ASP.NET",
    name: "Woodland-Wanderer",
    url: "https://github.com/W3ndig0u0/Woodland-Wanderer",
    desc: "2D action-platformer utvecklad i Unity.",
    topics: ["unity", "platformer", "2d"],
    status: "active",
  },
  {
    lang: "C#",
    name: "Dungeon-Generation",
    url: "https://github.com/W3ndig0u0/Dungeon-Generation",
    desc: "Procedurmässig dungeon-generator i Unity.",
    topics: ["unity", "procedural-generation"],
    status: "archived",
  },
  {
    lang: "C#",
    name: "HighSchoolFpsProject",
    url: "https://github.com/W3ndig0u0/HighSchoolFpsProject",
    desc: "Tidigt FPS-projekt från gymnasiet.",
    topics: ["unity", "fps", "legacy"],
    status: "archived",
  },
  {
    lang: "C#",
    name: "Onigiri-Escape-Japan",
    url: "https://github.com/W3ndig0u0/Onigiri-Escape-Japan",
    desc: "Unreal Engine-spel utvecklat i japanskt samarbetsprojekt.",
    topics: ["unreal-engine", "game-dev"],
    status: "archived",
  },
  {
    lang: "C++",
    name: "Rpg_Terminal_Cpp",
    url: "https://github.com/W3ndig0u0/Rpg_Terminal_Cpp",
    desc: "Terminalbaserat RPG för att lära C++.",
    topics: ["cpp", "terminal", "rpg"],
    status: "archived",
  },
  {
    lang: "C#",
    name: "VinterProjekt-Console-Tetris",
    url: "https://github.com/W3ndig0u0/VinterProjekt-Console-Tetris",
    desc: "Klassisk Tetris-klon för terminalen.",
    topics: ["csharp", "tetris", "console"],
    status: "archived",
  },
  {
    lang: "HTML",
    name: "Personlig-hemsida",
    url: "https://github.com/W3ndig0u0/Personlig-hemsida",
    desc: "Min första personliga webbplats.",
    topics: ["html", "portfolio"],
    status: "archived",
  },
  {
    lang: "HTML",
    name: "Pokemon",
    url: "https://github.com/W3ndig0u0/Pokemon",
    desc: "Statisk Pokémon-webbplats byggd med HTML, CSS och JavaScript.",
    topics: ["html", "css", "javascript"],
    status: "archived",
  },
  {
    lang: "Python",
    name: "FlappyBirdAI",
    url: "https://github.com/W3ndig0u0/FlappyBirdAI",
    desc: "Flappy Bird AI tränad med NEAT.",
    topics: ["python", "ai", "neat"],
    status: "archived",
  },
  {
    lang: "C#",
    name: "PokemonFps",
    url: "https://github.com/W3ndig0u0/PokemonFps",
    desc: "Pokémon FPS inspirerat av Call of Duty Zombies.",
    topics: ["unity", "pokemon", "fps"],
    status: "active",
  },
  {
    lang: "JavaScript",
    name: "jingchat",
    url: "https://github.com/W3ndig0u0/jingchat",
    desc: "Chattapplikation byggd med React och Firebase.",
    topics: ["react", "firebase", "chat"],
    status: "active",
  },
  {
    lang: "JavaScript",
    name: "pokedex",
    url: "https://github.com/W3ndig0u0/pokedex",
    desc: "Pokédex byggd i React.",
    topics: ["react", "pokemon"],
    status: "archived",
  },
  {
    lang: "Lua",
    name: "nvim-config",
    url: "https://github.com/W3ndig0u0/nvim-config",
    desc: "Personlig Neovim-konfiguration.",
    topics: ["neovim", "lua"],
    status: "archived",
  },
  {
    lang: "HTML",
    name: "MontanaResort",
    url: "https://github.com/W3ndig0u0/MontanaResort",
    desc: "Hotellwebbplats utvecklad under gymnasiet.",
    topics: ["html", "css"],
    status: "archived",
  },
  {
    lang: "C#",
    name: "vinterprojektet-3-DemonKing-Attack",
    url: "https://github.com/W3ndig0u0/vinterprojektet-3-DemonKing-Attack",
    desc: "Tidigt spelprojekt i C#.",
    topics: ["game-dev", "legacy"],
    status: "archived",
  },
  {
    lang: "C#",
    name: "VinterProjektet2",
    url: "https://github.com/W3ndig0u0/VinterProjektet2",
    desc: "Tidigt spelprojekt i C#.",
    topics: ["game-dev", "legacy"],
    status: "archived",
  },
  {
    lang: "JavaScript",
    name: "Chess",
    url: "https://github.com/W3ndig0u0/Chess",
    desc: "Tidigt schackprojekt i JavaScript.",
    topics: ["chess", "javascript"],
    status: "active",
  },
  {
    lang: "CSS",
    name: "Slime",
    url: "https://github.com/W3ndig0u0/Slime",
    desc: "Litet CSS-experiment.",
    topics: ["css"],
    status: "active",
  },
  {
    lang: "JavaScript",
    name: "Spel-hemsida",
    url: "https://github.com/W3ndig0u0/Spel-hemsida",
    desc: "Tidig spelwebbplats byggd i JavaScript.",
    topics: ["javascript", "web"],
    status: "active",
  },
];
